# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CGO build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  cgo-action:
    strategy:
      matrix:
        targets:
          - 'linux-arm64'
          - 'linux-amd64'
    name: Build Go Program
    runs-on: ubuntu-latest

    steps:
      - name: Setup GStreamer
        id:   setup_gstreamer
        uses: blinemedical/setup-gstreamer@1.0
        with:
          version: '1.24.12'
                
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build go program
        id: cgo-action
        uses: go-cross/cgo-actions@v1
        with:
          dir: '.'
          targets: ${{ matrix.targets }}

      - name: Print Output
        id: output
        run: ls - lah
        
